### ISSUE TITLE
EMAIL domains

### ISSUE THREAD

**Issue by Techpro709** [thedev-id/thedev.id#636]
Wanted to know if you guys support these records
<img width="691" alt="image" src="https://github.com/thedev-id/thedev.id/assets/61668117/b4ceb862-3570-41e4-a0cd-940829321019">

**Comment by Techpro709** [comment]
Also note, this is an example with the is-a.dev domain, I am still trying to contact them about the same question.

**Comment by lakuapik** [comment]
unfornately, right now we do not support MX record.
