### ISSUE TITLE
Dealing with Let’s Encrypt rate limits

### ISSUE THREAD

**Issue by fu-sen** [thedev-id/thedev.id#79]
I checked [past issues](https://github.com/fransallen/thedev.id/issues/64). You don't seem to know the Let’s Encrypt rate limits:
https://letsencrypt.org/docs/rate-limits/

This means that `SUBDOMAIN.thedev.id` will limit the issuance or renewal of Let’s Encrypt certificates.
It is necessary to deal with this.

[JS.ORG](https://js.org/), which is well known as a similar service, is on the [Public Suffix List](https://publicsuffix.org/). This makes Let’s Encrypt the same as ICANN Domains.
Or you need to submit to the [rate limiting form](https://letsencrypt.org/docs/rate-limits/#a-id-overrides-a-overrides).

[ZeroSSL](https://zerossl.com/) does not have this limitation, but the web service recommended by thedev.id does not seem to provide it.

**Comment by Codeize** [comment]
We do not provide any form of SSL encryption. That is down to the user to handle.

**Comment by fu-sen** [comment]
I repeat. This is something you have to consider at your level. Equivalent to hosting services. If you do not, you will soon receive confusion about this.

**Comment by Codeize** [comment]
So if I'm reading correctly, the current limit is 50 per week for us? Or 50 per week when we register?

**Comment by fu-sen** [comment]
As you read the text, I realize that you have begun to understand it. GitHub Pages and Vercel publish Let's Encrypt. If you run into this issue, you cannot handle it. You can deal with it by providing the domain!

**Comment by fransallen** [comment]
Hey @fu-sen thanks for reporting this. I'm aware of the LE rate limits, it's just that we don't have many subdomains at the moment. However, I'll try to submit thedev.id to the publicsuffix.org list. I'll keep this one open and thanks again.

**Comment by fu-sen** [comment]
Yes. This will probably take days. It's too late to deal with the problem once it appears. This should have been addressed now that there are still few subdomains.

**Comment by jaikrishna-tavva9** [comment]
k

**Comment by fu-sen** [comment]
It is currently recommended to apply for Let ’s Encrypt to resolve this issue. Now that this is possible, the Public Suffix List will not register for Let ’s Encrypt.

[HelioHost](https://www.heliohost.org/) recently encountered this issue. Root Admin here solved the problem with a Let's Encrypt application. 
https://www.helionet.org/index/topic/52997-lets-encrypt-rate-limit/
https://www.helionet.org/index/topic/53298-great-ssl-news/
Thedev.id should be able to do the same.

**Comment by fransallen** [comment]
Thanks @fu-sen for the guide. Will try to contact the LE team to request a rate limit increase now. I'll share it here when I hear from them.

**Comment by chez14** [comment]
Hi @fransallen,

You might want to add your domain to public suffix list too. Afaik Let's Encrypt respect the [Public Suffix](https://publicsuffix.org/) list that are maintained by Mozilla Foundation ([Reference](https://letsencrypt.org/docs/rate-limits/#:~:text=We%20use%20the%20Public%20Suffix%20List%20to%20calculate%20the%20registered%20domain)) to check if your domain is actually owned by you or it's actually public suffix domain that people can register "freely".

Thanks!

Ref: 
- https://publicsuffix.org/
- https://github.com/publicsuffix/list
- https://github.com/google/guava/wiki/InternetDomainNameExplained#public-suffixes-and-private-domains


And here's proposal sample:
- https://github.com/publicsuffix/list/pull/1571
- https://github.com/publicsuffix/list/pull/1553

**Comment by reed-jones** [comment]
would a simple letsencrypt wildcard cert help here?
